### ISSUE TITLE
running start_flika() multiple times leads to expanding menus

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#14]
If you open a command prompt, navigate to flika's directory, start python, and run:

```python
from flika import *
start_flika()
start_flika()
```
The top level menu items "Image, Process" get added over and over again.

**Comment by BrettJSettle** [comment]
Assert statement in the FlikaApplication __init__ checks if the main gui has already started, and a check in setup_menus to only make menus once.
