### ISSUE TITLE
checkUpdates() function doesn't work

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#15]
crashes with: 

```python
Traceback (most recent call last):
  File "C:\Users\kyle\Documents\GitHub\flika\flika\global_vars.py", line 199, in checkUpdates
    version = re.findall(r'version=([\d\.]*)', open('flika.py', 'r').read()[:100])
FileNotFoundError: [Errno 2] No such file or directory: 'flika.py'
```

**Comment by BrettJSettle** [comment]
Version compare works, but uninstalling and reinstalling Flika is tricky

**Comment by kyleellefsen** [comment]
We need to check if the currently running version of flika is installed via pip or not. If it is, 

```pip install -U flika. ```

If it's not, upgrade the way we have it now. 

Telling people they need to manually restart flika is fine for now.

**Comment by kyleellefsen** [comment]
This works now.
