### ISSUE TITLE
Plugin Manager UI

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#17]
When the plugin manager opens, the 'Update', 'Documentation', and 'Download' buttons are present before any plugin is selected. These should be removed. 

Also, before any plugin is selected we should have a button that opens a link in a browser that tells you how to submit a new plugin, and a link that goes to a page which has instructions on how to make a plugin. Since we haven't written the pages yet, just point them to a random website and we'll change them later.

**Comment by BrettJSettle** [comment]
Plugin Manager now has a standard screen that is displayed when it opens and a "New Plugin" button that links to the template page.
