### ISSUE TITLE
Bug installing plugins on Mac

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#19]
This is the exception I get trying to install a plugin on a Mac. 

<img width="711" alt="screen shot 2017-03-21 at 8 43 17 am" src="https://cloud.githubusercontent.com/assets/5554004/24156988/6b0c3bb4-0e15-11e7-8fdb-8da23c96f9d2.png">

**Comment by BrettJSettle** [comment]
This is a result of compiled python files from an older version of Python.  The .pyc files have a header that specifies the version of Python.  Remove the .pyc files to resolve this issue.
