### ISSUE TITLE
'Plugins' and 'Scripts' Menu don't load in OSX

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#21]

**Comment by BrettJSettle** [comment]
Is there any error that shows up?

**Comment by kyleellefsen** [comment]
No, no error. Those two items are just missing from the menu.

**Comment by kyleellefsen** [comment]
I discovered the problem. In OS X if there is nothing inside a top level menu, the menu is not displayed. Because the scripts and plugins menus get built on "aboutToShow" and the top level menu was hidden, they never got built. 

I called ```self.menuBar().setNativeMenuBar(False)``` and that fixed it.
