### ISSUE TITLE
Pip installed Flika does not support drop events

### ISSUE THREAD

**Issue by BrettJSettle** [flika-org/flika#25]
Not just an issue with the console_scripts entry point for flika, also occurs when running from within the interpreter.

**Comment by kyleellefsen** [comment]
How is it run from the interpreter? This works for me when pip installed on OSX. I can run "flika" in the command line and I can drag and drop files into flika.

**Comment by BrettJSettle** [comment]
Exactly like that. On my laptop. and "g.m.acceptDrops()" returns True. But if I drag anything over Flika, the cursor turns into the not allowed symbol.

**Comment by kyleellefsen** [comment]
I just tested this on my Mac and on Windows and it works in both. Any idea what would be different on your system?

**Comment by BrettJSettle** [comment]
I really don't know. If seems to just be my desktop now. But you can close
the issue. I think it's not specific to flika

**Comment by kyleellefsen** [comment]
K
