### ISSUE TITLE
Problem with the functions (eg. Subtract/ Ratio)

### ISSUE THREAD

**Issue by kousikkun** [flika-org/flika#61]
I am unable to use the the basic functions for some reason on Ipython. - I already did "from flika import *" . Its giving 'ratio' 'subtract' as undefined. I am not sure if I am missing something. Thanks!

**Comment by kyleellefsen** [comment]
Hi @kousikkun, if you launch from within IPython, you need to also run `import flika` and then use the long name of the function. For subtract and ratio, these are `flika.process.subtract` and `flika.process.ratio`. The short names only work if you launch flika from a non-IPython terminal and you open the Script Editor. If you'd still like to use the shortened names, you can run in IPython:

```python
from flika.process import *
generate_random_image()
gaussian_blur(sigma=2)
```

For instance, I followed these steps and was able to use `ratio()`.

- Open a terminal on my Mac (Ventura 13.5.1).
- Clean install of python using a new venv (Python 3.11.7)
- Clean install of flika using and `pip install flika`
- Launch of IPython using `ipython` command in the terminal
- Launch of flika using `from flika import *; start_flika()`
- Importing flika using `from flika.process import *`
- Generate a random image using `generate_random_image(500, 20)`
- Applying the ratio function using `ratio(0, 100, 'average', 0, True)`

**Comment by kousikkun** [comment]
Hello! Thanks it works fine.

Best,

Kousik
